### PR TITLE
fix(edit form): Correct github generated message

### LINKED ISSUE #50: Display term relationships which are relevant in term creation form
### Edit:

`Is Identifier Of` does not exist yet, and should be created, the others have been done in #174

### Original post

The relationships showed in the form should be only the ones for the type of concept considered.
Here's a table of which relationship should be showed, depending on the type of concept the user suggests.
(Please not `Is Identifier Of` does not exist yet, and should be created).

|relationship|applicable to| status |
|---------------|-----------------| ----- |
|Parent|all| nothing to do |
|Has Topic|Operation, Data| done |
|Is Format Of|Format| done |
|Has Input|Operation| done |
|Has Output|Operation| done |
|Is Identifier Of|Identifier| to do |

### PR DESCRIPTION
**Pull request by HagerDakroury**
### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

closes #50 
(this fixes a bug blocking the closing of this issue, but all work related to the issue itself has already been done)

### Details

the bug is described in  https://github.com/edamontology/edam-browser/issues/50#issuecomment-864027843

**after the fix**

githublow

**bug details:**
1. all new terms (after the first parent) were inheriting the `data-selected` attribute from the cloned search-term. So, it was detected as a change from `data-initial` (even though the user didn't actually change any term) 
2. all new terms were named `parent-i`

### CODE REVIEW

File: js/edit.js [hunk 1]
```diff
@@ -100,7 +100,8 @@ function addTermField(container, kind, initial_term){
 
     $(".search-term[name="+kind+"-"+i+"]")
                 .val(initial_term?initial_term.text:"")
-                .attr('data-initial',initial_term?initial_term.data.uri:"");
+                .attr('data-initial',initial_term?initial_term.data.uri:"")
+                .attr("data-selected",initial_term?initial_term.data.uri:"");
```
Comment (bryan-brancotte) [inline js/edit.js:104]: Just for my understanding : I cannot find the scenario where it is needed, indeed we have `var val = ($(ids[i]).attr('data-selected') || $(ids[i]).val());` in the case the field is unchanged and thus data-select not set. 

Anyway good to have.

**Review by bryan-brancotte — APPROVED** [review]
thanks for fixing it !

File: js/edit.js (hunk 1 above)
Comment (HagerDakroury) [reply js/edit.js:104]: yes, this line does exactly that well. The problem is `data-selected` is not initialized after [this line](https://github.com/edamontology/edam-browser/blob/739d46d5e9499b295cf300bb4c975a97624b3674/js/edit.js#L97) and hence, it always has the value of the first parent.
Once you remove this line I added above and debug the `data-selected` value for any term other than the first parent, you'll find it having the value of the first parent.

Comment (HagerDakroury) [reply js/edit.js:104]: This is the reason why it shows parent-1 edited here even though I haven't edited the term (the new suggestion is parent-0 as inherited in clone). We can leave it blank (unset) but I followed the pattern [here](https://github.com/edamontology/edam-browser/blob/739d46d5e9499b295cf300bb4c975a97624b3674/js/edit.js#L47)
reporting

Comment (bryan-brancotte) [reply js/edit.js:104]: well found ! and thanks for the explanation !
