### PR TITLE
Alerts user when loading custom ontology fails!

### LINKED ISSUE #137: Inform user when loading ontology fails
I tried to load a custom ontology it was not functional as shown in the video attached below: 

https://user-images.githubusercontent.com/56053777/115600795-af35e280-a2fa-11eb-8e67-5842bd668d26.mp4

Can @matuskalas @hmenager @bryan-brancotte assign me this so I'll start working on it asap!

### PR DESCRIPTION
**Pull request by secrashi**
### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

fix #137

### CODE REVIEW

File: js/tree-edam-stand-alone.js [hunk 1]
```diff
@@ -99,7 +99,6 @@ function interactive_edam_browser(){
         __my_interactive_tree.textAccessor(text_accessor_mapping[getUrlParameter("text_accessor")]);
 
         $("#myModal").modal('hide');
-        $("#edamAccordion>.panel-group").remove();
```
Comment (secrashi) [inline js/tree-edam-stand-alone.js:102]: I removed this code so that when custom ontology fails to load, the details section wouldn't be removed. But It will also keep it as previously seen terms when a custom ontology is loaded. I thought it is better to keep them as previously seen terms, then costing on our User experience, <as of now>.

**Review by bryan-brancotte — CHANGES_REQUESTED** [review]
Hi

Sorry for the long reviews. Please create a PR/new branch with only the changes in tree-reusable-d3.js so git history is intact.

File: js/tree-edam-stand-alone.js (hunk 1 above)
Comment (secrashi) [reply js/tree-edam-stand-alone.js:102]: Hi @bryan-brancotte, Yes I understand that previous ontology is not relevant while loading custom ontology, but the real question is are we ready to compromise our UI and UX for this? 
Please let me know if you don't think in similar way, I just thought that until we find a permanent (and better) solution to this, we can alter this to keep our UX the same.

Comment (bryan-brancotte) [reply js/tree-edam-stand-alone.js:102]: Hi @secrashi, keeping the old detail panel when failing at loading a new ontology is an UX issue : we were working with ontology A, we tried B, we thus must have information regarding B, or why it has failed to be loaded. You patch is to inform the user about failure of B, but removing this line also show information for A which is confusing. So in order to not compromoise the UX experience, we must not remove this line.

File: js/tree-edam-stand-alone.js [hunk 2]
```diff
@@ -109,12 +108,14 @@ function interactive_edam_browser(){
         reader.readAsText(file);
         reader.onload = function(event) {
             json = JSON.parse(event.target.result);
-            if(typeof json.meta=="undefined"){
```
[the remark this answers is not in the document]
Comment (secrashi) [reply js/tree-edam-stand-alone.js:112]: > Could you explain when this scenario occurs (json being null) ? 

Yes, Json would be null when we upload non-json files in the input field. 
>a simpler test on json == null and then returning would do the same and change less lines (thus keeping git history easily accessible)

Yes, I agree. I'll make this change asap. Also, I'm sorry for not taking git history into consideration. I'm not habitual of it but I'm learning. Thanks!
